language: scala

scala:
- 2.10.6
- 2.11.8

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - gem install jekyll -v 2.5

script:
  - sbt ++$TRAVIS_SCALA_VERSION "clean" "makeMicrosite"